name=input("What is your name?")
age=input("what is your age?")
country=input("which country are you from?")
qualification=input("what is your qualification?")
collegename=input("what is your college name?")
collegetype=input("Are you from Boys college?")
print(f"Hi, My name is  {name}")
print(f"I am from {country}")
print(f'I am {age} years old')
print(f"I am in {qualification}")
print(f"I studies in {collegename}")
print(f"It is a {collegetype}")

fir=int(input('First value'))
sec=int(input('second value'))
third=int(input('third value'))
print(fir * sec * third)
print(fir/sec/third)
print(fir+sec+third)
print(fir-sec-third)
